---
- hosts: galera_cluster
  roles:
    - { role: security, tags: [ 'setup' ] }
    - { role: galera_repos, tags: [ 'setup', 'packages' ] }
    - { role: galera_packages, tags: [ 'setup', 'packages' ] }
    - { role: galera_privs, tags: [ 'auth' ] }
    - { role: galera_conf, tags: [ 'config' ] }
  environment:
    http_proxy: http://10.0.191.5:3129
    https_proxy: http://10.0.191.5:3129
