---
- name: Start and enable ufw
  systemd: name=ufw state=stopped enabled=no

# - name: Open firewall for external access to MySQL
#   ufw: service=mysql permanent=true immediate=true state=enabled

# - name: Open Galera ports on firewall
#   ufw: from_port={{ item }} permanent=true immediate=true state=enabled
#   with_items:
#     - 4444/tcp
#     - 4567/tcp
#     - 4568/tcp

# - name: Disable SELinux
#   selinux: policy=targeted state=permissive
