---
- name: Install MariaDB server packages
  become: yes
  become_user: root
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - mariadb-client
    - mariadb-server
    - mariadb-client-core-{{ mariadb_release }}
    - galera-3
    - rsync

- name: Install mariadb-backup packages
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - mariadb-backup
    - socat

- name: Install MySQL-python
  become: yes
  become_user: root
  apt: name={{ item }} state=present
  with_items:
    - python-mysqldb
    - python-pymysql

