---
- name: Install MariaDB server packages
  apt: name={{ item }} state=present
  with_items:
    - MariaDB-client
    - MariaDB-server
    - galera
    - libmariadbclient18
    - rsync

- name: Install percona-xtrabackup packages
  apt: name={{ item }} state=present
  with_items:
    - percona-xtrabackup
    - socat
  when: "mariadb_release | version_compare('10.1', '<')"

- name: Install mariadb-backup packages
  apt: name={{ item }} state=present
  with_items:
    - mariadb-backup
    - socat
  when: "mariadb_release | version_compare('10.1', '>=')"

- name: Install MySQL-python
  apt: name=MySQL-python state=present
