---
- name: Install software-properties-common
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common

- name: Add MariaDB keys
  apt_key: 
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present

- name: Add MariaDB repo
  template: src=sources.list.d/mariadb.list.j2 dest=/etc/apt/sources.list.d/mariadb.list
    owner=root group=root mode=0644
