---
- name: Ensure MariaDB is running
  systemd:
    name: mariadb
    state: started

- name: Add Galera SST user
  mysql_user:
    login_user: root
    name: "{{ galera_sst_user }}"
    host: "localhost"
    password: "{{ galera_sst_pass }}"
    priv: "*.*:RELOAD,LOCK TABLES,REPLICATION CLIENT"
